Fix build due to `ht_*.h` move and non-use of llvm-config
rizinorg/rz-bindgen pull request #37
Opened 2023-10-25 15:30 UTC by kazarmy

This pr should fix the broken build due to

![ht-move-failure](https://github.com/rizinorg/rz-bindgen/assets/12002672/694af665-9fa4-47a2-ab3b-bdc918d966d9)
(https://github.com/rizinorg/rizin/actions/runs/6613041973/job/17960372892#step:7:46)

and #35, and should close #35, by changing some paths and using `llvm-config` (as per README.md) instead of whatever it's using right now.

2023-10-25 16:09 UTC, XVilka requested changes
```
 "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-tma2clor\cp38-win_amd64\build\venv\Scripts\python.exe" "../src/main.py" "-o" "." "--clang-path" "C:/Program Files/LLVM/bin" "--clang-args" " -resource-dir=C:/Program Files/LLVM/lib/clang/16" "--rizin-include-path" "C:rizin/include/librz" "--targets" "SWIG"
    warning: Files/LLVM/lib/clang/16: 'linker' input unused [-Wunused-command-line-argument]
    warning: Files/LLVM/lib/clang/16: 'linker' input unused [-Wunused-command-line-argument]
    warning: Files/LLVM/lib/clang/16: 'linker' input unused [-Wunused-command-line-argument]
    Traceback (most recent call last):
      File "../src/main.py", line 51, in <module>
        bindings.run()
      File "D:\a\rz-bindgen\rz-bindgen\src\bindings.py", line 51, in run
        func(Header(translation_unit, builder))
      File "D:\a\rz-bindgen\rz-bindgen\src\cparser_header.py", line 177, in __init__
        prev = self.cursors[cursor.kind][name]
    KeyError: 'RzAnalysisMetaUserItem'
  
    ninja: build stopped: subcommand failed.
    INFO: autodetecting backend as ninja
    INFO: calculating backend command to run: C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\ninja.EXE
    error: subprocess-exited-with-error
```
https://github.com/rizinorg/rz-bindgen/actions/runs/6642695802/job/18048044959?pr=37#step:4:4045

2023-10-26 01:43 UTC, wargio approved these changes

2023-10-26 01:47 UTC, wargio commented
the python lint issue is just a matter of config.

add `too-many-arguments` to the `pylintrc`

2023-10-26 01:49 UTC, wargio commented
The binding for windows is broken because of this

```
    Traceback (most recent call last):
      File "../src/main.py", line 51, in <module>
        bindings.run()
      File "D:\a\rz-bindgen\rz-bindgen\src\bindings.py", line 51, in run
        func(Header(translation_unit, builder))
      File "D:\a\rz-bindgen\rz-bindgen\src\cparser_header.py", line 177, in __init__
        prev = self.cursors[cursor.kind][name]
    KeyError: 'RzAnalysisMetaUserItem'
```

2023-10-26 07:23 UTC, ret2libc reviewed
Great!! Thanks a lot @kazarmy

2023-10-26 15:00 UTC, kazarmy commented
The Clang path didn't change between [the last Windows green build on master](https://github.com/rizinorg/rz-bindgen/actions/runs/5794183038/job/15703277557#step:4:3878) and [the broken Windows build here](https://github.com/rizinorg/rz-bindgen/actions/runs/6642695802/job/18048044959?pr=37#step:4:4033) so I'm pretty sure it's not me that caused the regression (unfortunately), therefore I'm merging this so that at least the Linux version builds.

2023-10-26 15:00 UTC, merged